name = "minecraft-modpack"
author = "patri"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2689957b3dd6c3f90cf07b34dea114cd68804cca7ee23b8030ad017e1e5abe25"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
