name = "minecraft-modpack"
author = "patri"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb2db4acdb4454a80ec8948d61caabbf76a263badd75d1c131c6c459e39b526f"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
