name = "minecraft-modpack"
author = "patri"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1e20fd4ea8b44f95a7284a76622edf75a4ea8f4a816ffe1745ef53e7d74de3d"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
